### ISSUE TITLE
'TemplateProxy' object has no attribute 'get_exception_info'

### ISSUE THREAD

**Issue by hvdklauw** [carltongibson/django-template-partials#1]
Happens when I used a model that wasn't migrated yet, so there was probably some underlaying database error.

The line that threw the error was the partial template tag.

**Comment by carltongibson** [comment]
OK, yes, that's for the debug template. (At least the bottom part of the traceback would be helpful.)

`TemplateProxy` should likely implement something here, so as not to error. 

Fancy doing that?

**Comment by hvdklauw** [comment]
Yes, was already looking at what was needed.

**Comment by carltongibson** [comment]
Great. Thanks. For first pass, something minimal would be enough. (I don't know we need to copy too much from Django...)
