### ISSUE TITLE
Check the token for partialdef inline

### ISSUE THREAD

**Issue by paulik123** [carltongibson/django-template-partials#45]
Hello, right now in order for a partialdef to be inline the check is very basic. The argument is only evaluated as a token, which is a string. The only condition is that some argument has to be there.

Relevant code:
```
    try:
        inline = tokens[2]
    except IndexError:
        # the inline argument is optional, so fallback to not using it
        inline = False
```
So even `{% partialdef some_partial False %}` will show the partial inline.

I think the inline argument should be a boolean. 
So you can render that partial conditionally like so:
`{% partialdef some_partial inline=some_true_or_false_condition %}`

**Comment by paulik123** [comment]
I've noticed also the partial name when using the partial templatetag is only parsed as a string. It would be nice if the arguments will be evaluated as variables.
`{% partial tab %}` # here tab evaluated as a string, not as a variable.

**Comment by carltongibson** [comment]
Hi @paulik123 — thanks for the report. 

To be honest I think the usage should just be `{% partialdef some_partial inline %}` — so passing the third argument trigger it. We could add a check for the literal value `'inline'` at that point, so I agree `False` is a little weird there. 

(If you want `False` just don't pass the argument, which is the default.) 

Make sense? Fancy making a PR?

**Comment by paulik123** [comment]
Thank you for the quick response and this awesome library. Sure, I'll come back with a PR.
