### ISSUE TITLE
Add support for blocks or slots

### ISSUE THREAD

**Issue by epicserve** [carltongibson/django-template-partials#56]
I started playing around with this project, and I do not see a way to define slots or blocks in the partial that would allow you to insert HTML or some other template context. Is something like the following possible, or do you have plans to add something like this in the future?

For example, if you had the template `index.html` with:

```
{% load partials %}

{% partialdef test-partial %}
  <div>TEST-PARTIAL-CONTENT</div>
  {% block extra_content %}{% endblock %}
{% endpartialdef test-partial %}

<p>Index View</p>
{% partial test-partial %}
  {% block extra_content %}<div>Extra Content</div>{% endblock %}
{% endpartial %}

{% partial test-partial %}
  {% block extra_content %}<div>Different Extra Content</div>{% endblock %}
{% endpartial %}
```

It could then render the following:
```
<p>Index View</p>

<div>TEST-PARTIAL-CONTENT</div>
<div>Extra Content</div>

<div>TEST-PARTIAL-CONTENT</div>
<div>Different Extra Content</div>
```

**Comment by carltongibson** [comment]
Hi. That kind of usage is out of scope for template-partials. 

I know the slippers library provides simpler to what you describe there. 

https://mitchel.me/slippers/

**Comment by epicserve** [comment]
@carltongibson, thank you. I'll take a look and try it out.

**Comment by carltongibson** [comment]
Great. Good luck.
