### ISSUE TITLE
Testing partial rendering fails with `self.assertTemplateUsed`

### ISSUE THREAD

**Issue by christophehenry** [carltongibson/django-template-partials#58]
`self.assertTemplateUsed` looks [for `templates` in `response`](https://github.com/django/django/blob/main/django/test/testcases.py#L756-L761) which is an empty list when rendering partials. Is it a bug or there's another recommanded way to test?

**Comment by carltongibson** [comment]
Hi @christophehenry. This is #54. 

> Until we can merge into Django (refs https://github.com/carltongibson/django-template-partials/issues/29) it's likely a [test runner subclass overriding the appropriate hook](https://docs.djangoproject.com/en/5.1/topics/testing/advanced/#django.test.runner.DiscoverRunner.setup_test_environment) would be needed here. Would you fancy having a look at that?
